FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o fizzbuzz

FROM gcr.io/distroless/static
WORKDIR /app
COPY --from=builder /app/fizzbuzz .
COPY --from=builder /app/templates /app/templates

EXPOSE 8080
ENTRYPOINT ["/app/fizzbuzz", "serve", "--port", "8080"]

