FROM golang:1.22 AS builder

WORKDIR /app
COPY . .
RUN go build -o app .

FROM scratch

COPY --from=builder /app/app /app
COPY --from=builder /app/templates/index.html /templates/index.html
WORKDIR /
CMD ["/app"]
